config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :orders
  resources :addresses
  resources :products_ordereds
  resources :prices
  resources :products do
    member do
      post :add_to_cart
    end
  end
  resources :categories
  resources :comments
  resources :cards
  resources :customers
  resources :admins
  resource :cart, only: [:show] do
    post 'update_quantity', on: :collection
    member do
      get :check_out
      post 'update_address'
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  delete 'cart/remove_item', to: 'carts#remove_item', as: 'remove_item_cart'
  post 'cart/place_order', to: 'carts#place_order', as: :place_order

  #post 'cart/update_quantity', to: 'cart#update_quantity', as: 'update_quantity_cart'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  validates :province, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :customer
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "desc", "id", "name", "updated_at"]
  end

  has_many :products
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customers
  belongs_to :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cards
  has_many :comments
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customers
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "desc", "id", "name", "price", "updated_at"]
  end

  belongs_to :category
  has_many :products_ordered
  has_many :comments
  has_one_attached :image

  validates :name,presence: true
  validates :price,  numericality: { only_integer: true, greater_than_or_equal_to: 0 }





end

app/models/products_ordered.rb
class ProductsOrdered < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Devise modules...
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :addresses
  # Additional attributes
  attr_accessor :name, :date_of_birth, :phone_number, :address, :postal, :province
  def self.ransackable_associations(auth_object = nil)
    []
  end
  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

end

app/controllers/products_ordereds_controller.rb
class ProductsOrderedsController < ApplicationController
  before_action :set_products_ordered, only: %i[ show edit update destroy ]

  # GET /products_ordereds or /products_ordereds.json
  def index
    @products_ordereds = ProductsOrdered.all
  end

  # GET /products_ordereds/1 or /products_ordereds/1.json
  def show
  end

  # GET /products_ordereds/new
  def new
    @products_ordered = ProductsOrdered.new
  end

  # GET /products_ordereds/1/edit
  def edit
  end

  # POST /products_ordereds or /products_ordereds.json
  def create
    @products_ordered = ProductsOrdered.new(products_ordered_params)

    respond_to do |format|
      if @products_ordered.save
        format.html { redirect_to products_ordered_url(@products_ordered), notice: "Products ordered was successfully created." }
        format.json { render :show, status: :created, location: @products_ordered }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @products_ordered.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products_ordereds/1 or /products_ordereds/1.json
  def update
    respond_to do |format|
      if @products_ordered.update(products_ordered_params)
        format.html { redirect_to products_ordered_url(@products_ordered), notice: "Products ordered was successfully updated." }
        format.json { render :show, status: :ok, location: @products_ordered }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @products_ordered.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products_ordereds/1 or /products_ordereds/1.json
  def destroy
    @products_ordered.destroy

    respond_to do |format|
      format.html { redirect_to products_ordereds_url, notice: "Products ordered was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_products_ordered
      @products_ordered = ProductsOrdered.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def products_ordered_params
      params.require(:products_ordered).permit(:order_id, :product_id, :quantity, :comments)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/products_ordereds_helper.rb
module ProductsOrderedsHelper
end

app/views/products_ordereds/_form.html.erb
<%= form_with(model: products_ordered) do |form| %>
  <% if products_ordered.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(products_ordered.errors.count, "error") %> prohibited this products_ordered from being saved:</h2>

      <ul>
        <% products_ordered.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_id, style: "display: block" %>
    <%= form.number_field :order_id %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.number_field :product_id %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :comments, style: "display: block" %>
    <%= form.text_field :comments %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products_ordereds/_products_ordered.html.erb
<div id="<%= dom_id products_ordered %>">
  <p>
    <strong>Order:</strong>
    <%= products_ordered.order_id %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= products_ordered.product_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= products_ordered.quantity %>
  </p>

  <p>
    <strong>Comments:</strong>
    <%= products_ordered.comments %>
  </p>

</div>

app/views/products_ordereds/edit.html.erb
<h1>Editing products ordered</h1>

<%= render "form", products_ordered: @products_ordered %>

<br>

<div>
  <%= link_to "Show this products ordered", @products_ordered %> |
  <%= link_to "Back to products ordereds", products_ordereds_path %>
</div>

app/views/products_ordereds/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products ordereds</h1>

<div id="products_ordereds">
  <% @products_ordereds.each do |products_ordered| %>
    <%= render products_ordered %>
    <p>
      <%= link_to "Show this products ordered", products_ordered %>
    </p>
  <% end %>
</div>

<%= link_to "New products ordered", new_products_ordered_path %>

app/views/products_ordereds/new.html.erb
<h1>New products ordered</h1>

<%= render "form", products_ordered: @products_ordered %>

<br>

<div>
  <%= link_to "Back to products ordereds", products_ordereds_path %>
</div>

app/views/products_ordereds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @products_ordered %>

<div>
  <%= link_to "Edit this products ordered", edit_products_ordered_path(@products_ordered) %> |
  <%= link_to "Back to products ordereds", products_ordereds_path %>

  <%= button_to "Destroy this products ordered", @products_ordered, method: :delete %>
</div>