config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :orders
  resources :addresses
  resources :products_ordereds
  resources :prices
  resources :products do
    member do
      post :add_to_cart
    end
  end
  resources :categories
  resources :comments
  resources :cards
  resources :customers
  resources :admins
  resource :cart, only: [:show] do
    post 'update_quantity', on: :collection
    member do
      get :check_out
      post 'update_address'
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  delete 'cart/remove_item', to: 'carts#remove_item', as: 'remove_item_cart'
  post 'cart/place_order', to: 'carts#place_order', as: :place_order

  #post 'cart/update_quantity', to: 'cart#update_quantity', as: 'update_quantity_cart'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  validates :province, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :customer
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "desc", "id", "name", "updated_at"]
  end

  has_many :products
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customers
  belongs_to :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cards
  has_many :comments
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customers
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "desc", "id", "name", "price", "updated_at"]
  end

  belongs_to :category
  has_many :products_ordered
  has_many :comments
  has_one_attached :image

  validates :name,presence: true
  validates :price,  numericality: { only_integer: true, greater_than_or_equal_to: 0 }





end

app/models/products_ordered.rb
class ProductsOrdered < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Devise modules...
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :addresses
  # Additional attributes
  attr_accessor :name, :date_of_birth, :phone_number, :address, :postal, :province
  def self.ransackable_associations(auth_object = nil)
    []
  end
  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  GST = 5
  State_tax =  {
    "Alberta" => 0,
    "British Columbia" => 7,
    "Manitoba" => 7,
    "New Brunswick" => 10,
    "Newfoundland and Labrador" => 10,
    "Northwest Territories" => 0,
    "Nova Scotia" => 10,
    "Nunavut" => 0,
    "Ontario" => 8,
    "Prince Edward Island" => 10,
    "Quebec" => 9.975,
    "Saskatchewan" => 6,
    "Yukon" => 0
  }

  def place_order
    # Retrieve address data from the session
    if user_signed_in?
      Address.create!(
        address: session[:address],
        postal: session[:postal],
        province: session[:province],
        user_id: current_user.id
      )
    end

    # Clear other relevant session data (e.g., cart)
    session.delete(:cart)
    session.delete(:address) # Optional: Clear the address from the session


    redirect_to products_path, notice: "Order placed successfully!"
  end


  def update_address
    @address = params[:address]
    @postal_code = params[:postal_code]
    @province = params[:province]

    session[:address] = @address
    session[:postal_code] = @postal_code
    session[:province] = @province

    redirect_to check_out_cart_path
  end


  def update_quantity
    product_id = params[:product_id]
    new_quantity = params[:quantity].to_i

    cart = session[:cart] || {}
    cart[product_id] = new_quantity
    session[:cart] = cart

    redirect_to cart_path, notice: 'Cart updated'
  end

  def remove_item
    product_id = params[:product_id]

    cart = session[:cart] || {}
    cart.delete(product_id)
    session[:cart] = cart

    redirect_to cart_path, notice: 'Item removed from cart'
  end

  def show
    @cart_contents = session[:cart] || {} # Retrieve cart contents from session
  end

  def check_out
    @cart_contents = session[:cart] || {}
    @address = session[:address]
    @postal_code = session[:postal_code]
    @province = session[:province]


  end
  def checkout_params
    params.require(:checkout).permit(:address, :postal_code, :province)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_address_form.html.erb
<%= form_tag update_address_cart_path, method: :post do %>
  <%= label_tag :address, "Address" %>
  <%= text_field_tag :address, @address ,required: true %>

  <%= label_tag :postal_code, "Postal Code" %>
  <%= text_field_tag :postal_code, @postal_code %>

  <%= label_tag :province, "Province" %>
  <%= select_tag :province, options_for_select(["Newfoundland and Labrador", "Nova Scotia", "Prince Edward Island", "New Brunswick", "Ontario", "Quebec", "Manitoba", "Saskatchewan", "Alberta", "British Columbia"]), selected: @province %>

  <%= submit_tag "Update Address" %>
  <% end %>

app/views/carts/check_out.html.erb
<h1>Your Order</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total Price</th>

    </tr>
  </thead>
  <tbody>
    <% total_price = 0 %>
    <% @cart_contents.each do |product_id, quantity| %>
      <% product = Product.find(product_id) %>
      <tr>
        <td><%= product.name %></td>
        <td><%= quantity %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= number_to_currency(product.price * quantity) %></td>
        <% total_price += (product.price * quantity) %>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="container">


<% @present_address = nil %>
<% if user_signed_in? %>

  <% now_user = User.find_by_id(current_user.id) %>
  <% @present_address = Address.where(user_id: current_user.id) %>

<% end %>

<% if @present_address.any?  %>
    <p>Address: <%= @present_address[0].address %></p>
    <p>Postal: <%= @present_address[0].postal %></p>
    <p>Province: <%= @present_address[0].province %></p>


    <div class="container">
        GST: <%= number_to_currency(CartsController::GST * total_price /100 )%>
        <br>
          HST/PST: <%= number_to_currency(CartsController::State_tax[@present_address[0].province] *total_price / 100)%>
        <br>
        Total: <%=  number_to_currency(total_price +CartsController::State_tax[@present_address[0].province] *total_price / 100 + CartsController::GST * total_price /100 ) %>
    </div>

    <%= form_tag place_order_path, method: :post do %>
      <%= submit_tag "Place Order" %>
    <% end %>





<% else %>
  <% if @address.present? %>
    <div>
      GST: <%= number_to_currency(CartsController::GST * total_price /100 )%>
      <br>
        HST/PST: <%= number_to_currency(CartsController::State_tax[@province] *total_price / 100)%>
      <br>
      Total: <%=  number_to_currency(total_price +CartsController::State_tax[@province] *total_price / 100 + CartsController::GST * total_price /100 ) %>
    </div>


    <div class="container">
    <h3>Shipping Address</h3>
    <p><strong>Address:</strong> <%= @address %></p>
    <p><strong>Postal Code:</strong> <%= @postal_code %></p>
    <p><strong>Province:</strong> <%= @province %></p>

    <%= form_tag place_order_path, method: :post do %>
    <%= submit_tag "Place Order" %>
  <% end %>

    </div>
  <% else%>
    <%= render "address_form" %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<% if session[:cart].present? %>
  <h1>Your Cart</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @cart_contents.each do |product_id, quantity| %>
      <% product = Product.find(product_id) %>
      <tr>
        <td><%= product.name %></td>
        <td>
          <%= form_tag update_quantity_cart_path, method: :post do %>
            <%= hidden_field_tag 'product_id', product_id %>
            <%= number_field_tag 'quantity', quantity, min: 1 %>
            <%= submit_tag 'Update' %>
          <% end %>
        </td>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= number_to_currency(product.price * quantity) %></td>
        <td>
          <%= button_to 'Remove', remove_item_cart_path(product_id: product_id), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Proceed to Checkout", check_out_cart_path, class: "btn btn-primary" %>

<%= link_to 'Continue Shopping', products_path %>

<% else %>
  <p>Your cart is empty.</p>
<% end %>