config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :orders
  resources :addresses
  resources :products_ordereds
  resources :prices
  resources :products do
    member do
      post :add_to_cart
    end
  end
  resources :categories
  resources :comments
  resources :cards
  resources :customers
  resources :admins
  resource :cart, only: [:show] do
    post 'update_quantity', on: :collection
    member do
      get :check_out
      post 'update_address'
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  delete 'cart/remove_item', to: 'carts#remove_item', as: 'remove_item_cart'
  post 'cart/place_order', to: 'carts#place_order', as: :place_order

  #post 'cart/update_quantity', to: 'cart#update_quantity', as: 'update_quantity_cart'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  validates :province, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :customer
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "desc", "id", "name", "updated_at"]
  end

  has_many :products
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customers
  belongs_to :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cards
  has_many :comments
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customers
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "desc", "id", "name", "price", "updated_at"]
  end

  belongs_to :category
  has_many :products_ordered
  has_many :comments
  has_one_attached :image

  validates :name,presence: true
  validates :price,  numericality: { only_integer: true, greater_than_or_equal_to: 0 }





end

app/models/products_ordered.rb
class ProductsOrdered < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Devise modules...
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :addresses
  # Additional attributes
  attr_accessor :name, :date_of_birth, :phone_number, :address, :postal, :province
  def self.ransackable_associations(auth_object = nil)
    []
  end
  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to card_url(@card), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:number, :address, :cvv, :exp_date, :customer_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cards/_card.html.erb
<div id="<%= dom_id card %>">
  <p>
    <strong>Number:</strong>
    <%= card.number %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= card.address %>
  </p>

  <p>
    <strong>Cvv:</strong>
    <%= card.cvv %>
  </p>

  <p>
    <strong>Exp date:</strong>
    <%= card.exp_date %>
  </p>

  <p>
    <strong>Customer:</strong>
    <%= card.customer_id %>
  </p>

</div>

app/views/cards/_form.html.erb
<%= form_with(model: card) do |form| %>
  <% if card.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :cvv, style: "display: block" %>
    <%= form.number_field :cvv %>
  </div>

  <div>
    <%= form.label :exp_date, style: "display: block" %>
    <%= form.date_field :exp_date %>
  </div>

  <div>
    <%= form.label :customer_id, style: "display: block" %>
    <%= form.number_field :customer_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Show this card", @card %> |
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cards</h1>

<div id="cards">
  <% @cards.each do |card| %>
    <%= render card %>
    <p>
      <%= link_to "Show this card", card %>
    </p>
  <% end %>
</div>

<%= link_to "New card", new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @card %>

<div>
  <%= link_to "Edit this card", edit_card_path(@card) %> |
  <%= link_to "Back to cards", cards_path %>

  <%= button_to "Destroy this card", @card, method: :delete %>
</div>